"""Stable, sanitized application errors and degraded-mode policy."""

from enum import Enum

from app.config import get_settings


class ErrorCode(str, Enum):
    CFG_UNSUPPORTED_PYTHON = "CFG_UNSUPPORTED_PYTHON"
    CFG_INVALID_APP_MODE = "CFG_INVALID_APP_MODE"
    CFG_INVALID_DB_TYPE = "CFG_INVALID_DB_TYPE"
    CFG_DATABASE_URL_MISMATCH = "CFG_DATABASE_URL_MISMATCH"
    CFG_PRODUCTION_DEGRADED_FORBIDDEN = "CFG_PRODUCTION_DEGRADED_FORBIDDEN"
    CFG_PRODUCTION_EPHEMERAL_STORAGE = "CFG_PRODUCTION_EPHEMERAL_STORAGE"
    CFG_LLM_API_KEY_MISSING = "CFG_LLM_API_KEY_MISSING"
    CFG_LLM_API_KEY_PLACEHOLDER = "CFG_LLM_API_KEY_PLACEHOLDER"
    CFG_LLM_ENDPOINT_INVALID = "CFG_LLM_ENDPOINT_INVALID"
    CFG_LLM_MODEL_MISSING = "CFG_LLM_MODEL_MISSING"
    CFG_INVALID_LLM_TIMEOUT = "CFG_INVALID_LLM_TIMEOUT"
    CFG_INVALID_LLM_RETRY_POLICY = "CFG_INVALID_LLM_RETRY_POLICY"
    CFG_INVALID_LLM_STRUCTURED_OUTPUT_MODE = "CFG_INVALID_LLM_STRUCTURED_OUTPUT_MODE"
    CFG_INVALID_LLM_TOKEN_LIMIT = "CFG_INVALID_LLM_TOKEN_LIMIT"
    CFG_INVALID_RETRIEVAL_POLICY = "CFG_INVALID_RETRIEVAL_POLICY"
    CFG_EMBEDDING_MODEL_MISSING = "CFG_EMBEDDING_MODEL_MISSING"
    EMBEDDING_MODEL_UNAVAILABLE = "EMBEDDING_MODEL_UNAVAILABLE"
    STORAGE_MEMORY_EPHEMERAL = "STORAGE_MEMORY_EPHEMERAL"
    STORAGE_SQLITE_PATH_UNWRITABLE = "STORAGE_SQLITE_PATH_UNWRITABLE"
    STORAGE_DATABASE_UNAVAILABLE = "STORAGE_DATABASE_UNAVAILABLE"
    VECTOR_DIRECTORY_UNWRITABLE = "VECTOR_DIRECTORY_UNWRITABLE"
    VECTOR_COLLECTION_MISSING = "VECTOR_COLLECTION_MISSING"
    VECTOR_COLLECTION_EMPTY = "VECTOR_COLLECTION_EMPTY"
    VECTOR_COLLECTION_METADATA_MISMATCH = "VECTOR_COLLECTION_METADATA_MISMATCH"
    VECTOR_STORE_UNAVAILABLE = "VECTOR_STORE_UNAVAILABLE"
    KNOWLEDGE_BASE_MANIFEST_INVALID = "KNOWLEDGE_BASE_MANIFEST_INVALID"
    RESOURCE_DIRECTORY_UNWRITABLE = "RESOURCE_DIRECTORY_UNWRITABLE"
    GENERATION_DEPENDENCY_UNAVAILABLE = "GENERATION_DEPENDENCY_UNAVAILABLE"
    LLM_UPSTREAM_UNAVAILABLE = "LLM_UPSTREAM_UNAVAILABLE"
    LLM_TIMEOUT = "LLM_TIMEOUT"
    LLM_RATE_LIMITED = "LLM_RATE_LIMITED"
    LLM_CONNECTION_FAILED = "LLM_CONNECTION_FAILED"
    LLM_UPSTREAM_5XX = "LLM_UPSTREAM_5XX"
    LLM_AUTH_FAILED = "LLM_AUTH_FAILED"
    LLM_BAD_REQUEST = "LLM_BAD_REQUEST"
    LLM_STRUCTURED_OUTPUT_UNSUPPORTED = "LLM_STRUCTURED_OUTPUT_UNSUPPORTED"
    LLM_OUTPUT_EMPTY = "LLM_OUTPUT_EMPTY"
    LLM_OUTPUT_TRUNCATED = "LLM_OUTPUT_TRUNCATED"
    LLM_OUTPUT_PARSE_FAILED = "LLM_OUTPUT_PARSE_FAILED"
    LLM_OUTPUT_SCHEMA_INVALID = "LLM_OUTPUT_SCHEMA_INVALID"
    LLM_CONTENT_REFUSED = "LLM_CONTENT_REFUSED"
    RETRIEVAL_UPSTREAM_UNAVAILABLE = "RETRIEVAL_UPSTREAM_UNAVAILABLE"
    RETRIEVAL_QUERY_INVALID = "RETRIEVAL_QUERY_INVALID"
    RETRIEVAL_SCORE_UNSUPPORTED = "RETRIEVAL_SCORE_UNSUPPORTED"
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"
    EVIDENCE_PROVENANCE_INVALID = "EVIDENCE_PROVENANCE_INVALID"
    EVIDENCE_SCOPE_VIOLATION = "EVIDENCE_SCOPE_VIOLATION"
    VECTOR_INDEX_OUT_OF_SYNC = "VECTOR_INDEX_OUT_OF_SYNC"
    KNOWLEDGE_INGESTION_FAILED = "KNOWLEDGE_INGESTION_FAILED"
    KNOWLEDGE_INGESTION_SMOKE_FAILED = "KNOWLEDGE_INGESTION_SMOKE_FAILED"
    CLAIM_CHECK_NOT_IMPLEMENTED = "CLAIM_CHECK_NOT_IMPLEMENTED"
    CLAIM_EXTRACTION_INVALID = "CLAIM_EXTRACTION_INVALID"
    CLAIM_JUDGEMENT_INVALID = "CLAIM_JUDGEMENT_INVALID"
    WORKFLOW_SCHEMA_UNSUPPORTED = "WORKFLOW_SCHEMA_UNSUPPORTED"
    WORKFLOW_CONTRACT_INVALID = "WORKFLOW_CONTRACT_INVALID"
    WORKFLOW_PERSISTENCE_UNAVAILABLE = "WORKFLOW_PERSISTENCE_UNAVAILABLE"
    WORKFLOW_PERSISTENCE_CONFLICT = "WORKFLOW_PERSISTENCE_CONFLICT"
    WORKFLOW_EVENT_SEQUENCE_CONFLICT = "WORKFLOW_EVENT_SEQUENCE_CONFLICT"
    WORKFLOW_CHECKPOINT_INVALID = "WORKFLOW_CHECKPOINT_INVALID"
    WORKFLOW_EVIDENCE_SNAPSHOT_CONFLICT = "WORKFLOW_EVIDENCE_SNAPSHOT_CONFLICT"
    WORKFLOW_RUN_NOT_FOUND = "WORKFLOW_RUN_NOT_FOUND"
    WORKFLOW_RUN_INTERRUPTED = "WORKFLOW_RUN_INTERRUPTED"
    WORKFLOW_FINALIZATION_FAILED = "WORKFLOW_FINALIZATION_FAILED"
    REQUEST_VALIDATION_ERROR = "REQUEST_VALIDATION_ERROR"
    HTTP_ERROR = "HTTP_ERROR"
    ADMIN_HEALTH_DISABLED = "ADMIN_HEALTH_DISABLED"
    ADMIN_UNAUTHORIZED = "ADMIN_UNAUTHORIZED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


PUBLIC_MESSAGES = {
    ErrorCode.GENERATION_DEPENDENCY_UNAVAILABLE: "生成依赖当前不可用",
    ErrorCode.LLM_UPSTREAM_UNAVAILABLE: "大模型服务当前不可用",
    ErrorCode.LLM_TIMEOUT: "大模型服务响应超时",
    ErrorCode.LLM_RATE_LIMITED: "大模型服务请求频率受限",
    ErrorCode.LLM_CONNECTION_FAILED: "无法连接大模型服务",
    ErrorCode.LLM_UPSTREAM_5XX: "大模型服务暂时异常",
    ErrorCode.LLM_AUTH_FAILED: "大模型服务认证失败",
    ErrorCode.LLM_BAD_REQUEST: "大模型请求不受支持",
    ErrorCode.LLM_STRUCTURED_OUTPUT_UNSUPPORTED: "当前模型不支持所需结构化输出模式",
    ErrorCode.LLM_OUTPUT_EMPTY: "大模型返回内容为空",
    ErrorCode.LLM_OUTPUT_TRUNCATED: "大模型返回内容不完整",
    ErrorCode.LLM_OUTPUT_PARSE_FAILED: "大模型返回格式无法解析",
    ErrorCode.LLM_OUTPUT_SCHEMA_INVALID: "大模型返回内容不符合约定结构",
    ErrorCode.LLM_CONTENT_REFUSED: "大模型拒绝生成该内容",
    ErrorCode.RETRIEVAL_UPSTREAM_UNAVAILABLE: "知识检索服务当前不可用",
    ErrorCode.RETRIEVAL_QUERY_INVALID: "知识检索查询无效",
    ErrorCode.RETRIEVAL_SCORE_UNSUPPORTED: "知识检索分数类型不受支持",
    ErrorCode.EVIDENCE_INSUFFICIENT: "当前知识证据不足，未生成事实资源",
    ErrorCode.EVIDENCE_PROVENANCE_INVALID: "知识证据来源不完整或无法验证",
    ErrorCode.EVIDENCE_SCOPE_VIOLATION: "知识证据超出当前知识库范围",
    ErrorCode.VECTOR_INDEX_OUT_OF_SYNC: "知识索引与目录数据不一致",
    ErrorCode.KNOWLEDGE_INGESTION_FAILED: "知识库入库失败",
    ErrorCode.KNOWLEDGE_INGESTION_SMOKE_FAILED: "知识库入库验证失败",
    ErrorCode.CLAIM_CHECK_NOT_IMPLEMENTED: "Claim 级审核能力尚未启用",
    ErrorCode.CLAIM_EXTRACTION_INVALID: "Claim 抽取结果无法验证",
    ErrorCode.CLAIM_JUDGEMENT_INVALID: "Claim 判定结果无法验证",
    ErrorCode.WORKFLOW_SCHEMA_UNSUPPORTED: "工作流契约版本不受支持",
    ErrorCode.WORKFLOW_CONTRACT_INVALID: "工作流状态校验失败",
    ErrorCode.WORKFLOW_PERSISTENCE_UNAVAILABLE: "工作流记录服务当前不可用",
    ErrorCode.WORKFLOW_PERSISTENCE_CONFLICT: "工作流记录发生一致性冲突",
    ErrorCode.WORKFLOW_EVENT_SEQUENCE_CONFLICT: "工作流事件序号冲突",
    ErrorCode.WORKFLOW_CHECKPOINT_INVALID: "工作流回放数据校验失败",
    ErrorCode.WORKFLOW_EVIDENCE_SNAPSHOT_CONFLICT: "工作流证据快照冲突",
    ErrorCode.WORKFLOW_RUN_NOT_FOUND: "工作流运行记录不存在",
    ErrorCode.WORKFLOW_RUN_INTERRUPTED: "工作流运行已中断",
    ErrorCode.WORKFLOW_FINALIZATION_FAILED: "工作流结果持久化失败",
    ErrorCode.REQUEST_VALIDATION_ERROR: "请求参数校验失败",
    ErrorCode.ADMIN_HEALTH_DISABLED: "管理员健康详情接口未启用",
    ErrorCode.ADMIN_UNAUTHORIZED: "管理员凭据无效",
    ErrorCode.INTERNAL_ERROR: "服务器内部错误，请稍后重试",
}


class ApplicationError(Exception):
    """An error safe to map to a stable public response."""

    def __init__(
        self,
        code: ErrorCode,
        public_message: str | None = None,
        status_code: int = 503,
    ):
        self.code = code
        self.public_message = public_message or PUBLIC_MESSAGES.get(code, "服务当前不可用")
        self.status_code = status_code
        super().__init__(code.value)


def require_degraded_generation(code: ErrorCode) -> str:
    """Allow a fallback only when the current non-production mode explicitly opts in."""
    settings = get_settings()
    if settings.app_mode == "production" or not settings.allow_degraded_generation:
        raise ApplicationError(code)
    return code.value
